### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by helloword12345678** [yyHaker/MachineComprehension#1]
感谢分享
请问该程序如何运行，有没有运行命令？

**Comment by MrTuo** [comment]
Duplicate of #1
运行search：python train.py -c du_config_search.json -d 0 -n first_run 
运行zhidao：python train.py -c du_config_zhidao.json -d 0 -n first_run 
详细的参数设置可以在train.py和du_config.json中看到

**Comment by MrTuo** [comment]
> 感谢分享
> 请问该程序如何运行，有没有运行命令？

运行search：python train.py -c du_config_search.json -d 0 -n first_run
运行zhidao：python train.py -c du_config_zhidao.json -d 0 -n first_run
详细的参数设置可以在train.py和du_config.json中看到
